name: projo
description: "A new Flutter project."
# Prevents the package from being accidentally published to pub.dev
publish_to: 'none'

# Versioning information
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Adjusted the version to match the GetX dependency

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.8

  # GetX for state management, theme, navigation
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter projects
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, uncomment and add your image paths
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts, uncomment and add your font paths
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic